### ISSUE TITLE
Error: `requests.exceptions.HTTPError: Invalid input.`

### ISSUE THREAD

**Issue by AnzenKodo** [younho9/notion2github#5]
The action is not working in my reop 
My Workflow
```yml
name: Notion2Github
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  auto-sync-from-notion-to-github:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Notion2Github
        uses: younho9/notion2github@v1.1.0
        with:
          database-url: 'https://www.notion.so/Filly-Agioro-6da28553362e403aabdbf6e6f137f7a4'
          docs-directory: docs
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}

      - name: Format documents
        uses: creyD/prettier_action@v3.1
        with:
          prettier_options: --write ./docs/**/*.md
          commit_message: 'docs: Update docs (auto)'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

It is showing me this error
```bash
Traceback (most recent call last):
  File "/usr/src/app/main.py", line 4, in <module>
    main()
  File "/usr/local/lib/python3.8/site-packages/narkdown/cli.py", line 63, in main
    exporter.get_notion_pages_from_database(database_url=url, **database_config)
  File "/usr/local/lib/python3.8/site-packages/narkdown/exporter.py", line 141, in get_notion_pages_from_database
    collection = self.client.get_block(database_url).collection
  File "/usr/local/lib/python3.8/site-packages/notion/client.py", line 169, in get_block
    block = self.get_record_data("block", block_id, force_refresh=force_refresh)
  File "/usr/local/lib/python3.8/site-packages/notion/client.py", line 162, in get_record_data
    return self._store.get(table, id, force_refresh=force_refresh)
  File "/usr/local/lib/python3.8/site-packages/notion/store.py", line 184, in get
    self.call_load_page_chunk(id)
  File "/usr/local/lib/python3.8/site-packages/notion/store.py", line 286, in call_load_page_chunk
    recordmap = self._client.post("loadPageChunk", data).json()["recordMap"]
  File "/usr/local/lib/python3.8/site-packages/notion/client.py", line 260, in post
    raise HTTPError(
requests.exceptions.HTTPError: Invalid input.
```

**Comment by younho9** [comment]
Database url should be url of notion database page. Your url is notion page. You can refer [this database page](https://www.notion.so/younho9/acc3dfd0339e4cacb5baae8673fddfad?v=be43c1c8dd644cfb9df9efd97d8af60a).

**Comment by AnzenKodo** [comment]
Oh Thanks
